---
  - name: 1.1.1 Create Separate Partition for /tmp (Scored)
    debug: msg="*** Manually create Separate Partition for /tmp."
    tags:
      - scored
      - section1.1
      - section1.1.1

  - name: 1.1.2 - 1.1.4 Set nodev,nosuid,noexec option for /tmp Partition (Scored)
    mount: >
      name="/tmp"
      src={{ item.device }}
      state=mounted
      fstype={{ item.fstype }}
      opts="nodev,nosuid,noexec"
    when: item.mount == "/tmp"
    with_items: "{{ansible_mounts}}"
    tags:
      - scored
      - section1.1
      - section1.1.2
      - section1.1.3
      - section1.1.4

  - name: 1.1.5 Create Separate Partition for /var (Scored)
    debug: msg="*** Manually create Separate Partition for /var."
    tags:
      - scored
      - section1.1
      - section1.1.5

  - name: 1.1.6 Bind Mount the /var/tmp directory to /tmp (Scored)
    mount: >
      name="/var/tmp"
      src="/tmp"
      state=mounted
      fstype="none"
      opts="bind"
    when: item.mount == "/tmp"
    with_items: "{{ansible_mounts}}"
    tags:
      - scored
      - section1.1
      - section1.1.6

  - name: 1.1.7 Create Separate Partition for /var/log (Scored)
    debug: msg="*** Manually create Separate Partition for /var/log."
    tags:
      - scored
      - section1.1
      - section1.1.7

  - name: 1.1.8 Create Separate Partition for /var/log/audit (Scored)
    debug: msg="*** Manually create Separate Partition for /var/log/audit."
    tags:
      - scored
      - section1.1
      - section1.1.8

